#!/usr/bin/env python3
"""Parse the fetched Google Fonts CSS, download the latin + latin-ext woff2
files locally, and emit @font-face rules pointing at /static/assets/fonts/."""
import re
import subprocess
from pathlib import Path


def fetch(url, dest):
    subprocess.run(
        ["curl", "-sSL", "-m", "60", url, "-o", str(dest)],
        check=True,
    )

FONTS_DIR = Path("/Users/alexis/Documents/GitHub/Lull-Mail-dev/frontend/assets/fonts")
CSS_IN = FONTS_DIR / "gfonts.css"
CSS_OUT = FONTS_DIR / "fonts.css"

SLUG = {"Plus Jakarta Sans": "jakarta", "JetBrains Mono": "jetbrains-mono"}
KEEP_SUBSETS = {"latin", "latin-ext"}

text = CSS_IN.read_text()

# Split into (subset_comment, block) pairs. Each @font-face is preceded by a
# `/* subset */` comment line.
parts = re.split(r"/\*\s*([a-z-]+)\s*\*/", text)
# parts = ['', subset1, block1, subset2, block2, ...]
blocks = []
for i in range(1, len(parts) - 1, 2):
    subset = parts[i].strip()
    block = parts[i + 1]
    blocks.append((subset, block))

out_rules = []
downloaded = 0
for subset, block in blocks:
    if subset not in KEEP_SUBSETS:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block)
    weight = re.search(r"font-weight:\s*(\d+)", block)
    style = re.search(r"font-style:\s*(\w+)", block)
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
    urange = re.search(r"unicode-range:\s*([^;]+);", block)
    if not (fam and weight and url):
        continue
    family = fam.group(1)
    slug = SLUG.get(family)
    if not slug:
        continue
    w = weight.group(1)
    st = style.group(1) if style else "normal"
    fname = f"{slug}-{w}-{subset}.woff2"
    dest = FONTS_DIR / fname
    if not dest.exists():
        fetch(url.group(1), dest)
        downloaded += 1
    rule = (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        f"  font-style: {st};\n"
        f"  font-weight: {w};\n"
        "  font-display: swap;\n"
        f"  src: url('/static/assets/fonts/{fname}') format('woff2');\n"
    )
    if urange:
        rule += f"  unicode-range: {urange.group(1).strip()};\n"
    rule += "}"
    out_rules.append(rule)

header = (
    "/* Self-hosted fonts (vendored from Google Fonts, latin + latin-ext).\n"
    "   Generated by scripts/vendor_fonts — do not edit by hand. */\n"
)
CSS_OUT.write_text(header + "\n" + "\n".join(out_rules) + "\n")
print(f"downloaded {downloaded} woff2 files")
print(f"wrote {len(out_rules)} @font-face rules to {CSS_OUT}")
